
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 05 16:55:24 CET 2023
//----------------------------------------------------

package com.lefc.jambly;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIU = 32;
  public static final int PLUSPLUS = 30;
  public static final int DIVISO = 34;
  public static final int STRING_LITERAL = 47;
  public static final int GTEQ = 38;
  public static final int LTEQ = 37;
  public static final int DOUBLE = 4;
  public static final int PRIVATE = 19;
  public static final int INT = 3;
  public static final int FOR = 28;
  public static final int STATIC = 20;
  public static final int BOOLEAN_LITERAL = 45;
  public static final int OROR = 42;
  public static final int CHARACTER_LITERAL = 46;
  public static final int LT = 35;
  public static final int MENO = 33;
  public static final int PER = 9;
  public static final int CLASS = 22;
  public static final int ANDAND = 41;
  public static final int NULL_LITERAL = 49;
  public static final int IF = 24;
  public static final int TONDA_CHIUSA = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int MINUSMINUS = 31;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int EQEQ = 39;
  public static final int VOID = 23;
  public static final int EQ = 13;
  public static final int TONDA_APERTA = 14;
  public static final int LBRACK = 5;
  public static final int IMPORT = 17;
  public static final int FLOATING_POINT_LITERAL = 44;
  public static final int LBRACE = 11;
  public static final int ELSE = 25;
  public static final int PUNTO = 7;
  public static final int RBRACK = 6;
  public static final int PACKAGE = 16;
  public static final int FINAL = 21;
  public static final int WHILE = 27;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 12;
  public static final int PUNTO_E_VIRGOLA = 8;
  public static final int GT = 36;
  public static final int VIRGOLA = 10;
  public static final int DO = 26;
  public static final int NOTEQ = 40;
  public static final int IDENTIFICATORE = 48;
  public static final int INTEGER_LITERAL = 43;
}

